name: Tests
on:
  workflow_dispatch:

jobs:
  step-one:
    name: Step one
    runs-on: ubuntu-latest
    steps:
      - name: Run
        id: step-one-1
        run: |
          echo "test step 1"
          echo "this should print stuff"

  step-two:
    name: Step two
    runs-on: ubuntu-latest
    needs: step-one
    steps:
      - name: Run test
        id: step-two-1
        run: |
          echo "test step 2"
          echo "this should print additional stuff"

